<?php

namespace Container5fAL78i;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCartsControllerService extends App_KernelDevContainer
{
    /*
     * Gets the public 'App\Controller\CartsController' shared autowired service.
     *
     * @return \App\Controller\CartsController
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = new \App\Service\CartsService();
        $a->setSecurity(($container->privates['security.helper'] ?? $container->load('getSecurity_HelperService')));
        $a->setEntityManager(($container->services['doctrine.orm.default_entity_manager'] ?? $container->getDoctrine_Orm_DefaultEntityManagerService()));

        $container->services['App\\Controller\\CartsController'] = $instance = new \App\Controller\CartsController($a);

        $instance->setContainer(($container->privates['.service_locator.jIxfAsi'] ?? $container->load('get_ServiceLocator_JIxfAsiService'))->withContext('App\\Controller\\CartsController', $container));

        return $instance;
    }
}
