parameters:
    mailer.data: 
        dest: '%env(MAILER_DEST)%'

services:
    _defaults:
        autowire: true      
        autoconfigure: true 
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/Dto'

    
    App\Service\NotificationService:
        arguments: 
            $mailerData: '%mailer.data%'
        

    _instanceof:
        Doctrine\Bundle\DoctrineBundle\Repository\ServiceEntityRepositoryInterface:
            autowire: true
            tags: ['doctrine.repository_service']
    
