<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container5fAL78i\App_KernelDevContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container5fAL78i/App_KernelDevContainer.php') {
    touch(__DIR__.'/Container5fAL78i.legacy');

    return;
}

if (!\class_exists(App_KernelDevContainer::class, false)) {
    \class_alias(\Container5fAL78i\App_KernelDevContainer::class, App_KernelDevContainer::class, false);
}

return new \Container5fAL78i\App_KernelDevContainer([
    'container.build_hash' => '5fAL78i',
    'container.build_id' => 'cb435ddb',
    'container.build_time' => 1678929686,
], __DIR__.\DIRECTORY_SEPARATOR.'Container5fAL78i');
